import { AITool } from "@/types/aiTool";

export const aiTools: AITool[] = [
  {
    id: 1,
    name: "ChatGPT",
    description: "AI assistant for writing, coding and research.",
    logo: "🤖",
    promptCount: "400K+",
    users: "200M+",
    rating: 4.9,
    color: "from-green-500 to-emerald-400",
  },
  {
    id: 2,
    name: "Claude",
    description: "Anthropic's AI assistant for long-form reasoning.",
    logo: "🧠",
    promptCount: "120K+",
    users: "30M+",
    rating: 4.8,
    color: "from-orange-500 to-yellow-400",
  },
  {
    id: 3,
    name: "Gemini",
    description: "Google's multimodal AI assistant.",
    logo: "💎",
    promptCount: "180K+",
    users: "90M+",
    rating: 4.8,
    color: "from-blue-500 to-cyan-400",
  },
  {
    id: 4,
    name: "Cursor",
    description: "AI-powered code editor for developers.",
    logo: "💻",
    promptCount: "95K+",
    users: "5M+",
    rating: 4.9,
    color: "from-violet-500 to-purple-500",
  },
  {
    id: 5,
    name: "Midjourney",
    description: "Create stunning AI-generated artwork.",
    logo: "🎨",
    promptCount: "210K+",
    users: "18M+",
    rating: 4.9,
    color: "from-pink-500 to-rose-500",
  },
  {
    id: 6,
    name: "Flux",
    description: "High-quality AI image generation.",
    logo: "✨",
    promptCount: "70K+",
    users: "4M+",
    rating: 4.7,
    color: "from-indigo-500 to-blue-500",
  },
  {
    id: 7,
    name: "Perplexity",
    description: "AI-powered search and research assistant.",
    logo: "🔍",
    promptCount: "60K+",
    users: "20M+",
    rating: 4.8,
    color: "from-sky-500 to-cyan-500",
  },
  {
    id: 8,
    name: "GitHub Copilot",
    description: "AI pair programmer for developers.",
    logo: "🐙",
    promptCount: "140K+",
    users: "15M+",
    rating: 4.9,
    color: "from-gray-700 to-gray-500",
  },
];