import { Creator } from "@/types/creator";

export const creators: Creator[] = [
  {
    id: 1,
    name: "Gopal Mahto",
    username: "@gopal",
    avatar: "👨‍💻",
    bio: "Java Developer & AI Prompt Engineer",
    specialization: "Development",
    followers: "12.5K",
    prompts: 420,
    rating: 4.9,
    verified: true,
  },
  {
    id: 2,
    name: "Alex Carter",
    username: "@alex",
    avatar: "🎨",
    bio: "Midjourney & Flux Artist",
    specialization: "Design",
    followers: "18K",
    prompts: 360,
    rating: 4.8,
    verified: true,
  },
  {
    id: 3,
    name: "Sarah Lee",
    username: "@sarah",
    avatar: "🧪",
    bio: "QA Automation Specialist",
    specialization: "Testing",
    followers: "9.2K",
    prompts: 280,
    rating: 4.9,
    verified: true,
  },
  {
    id: 4,
    name: "Emma Wilson",
    username: "@emma",
    avatar: "📈",
    bio: "AI Marketing Strategist",
    specialization: "Marketing",
    followers: "15K",
    prompts: 510,
    rating: 4.8,
    verified: true,
  },
  {
    id: 5,
    name: "John Smith",
    username: "@john",
    avatar: "💻",
    bio: "Full Stack Developer",
    specialization: "Web Development",
    followers: "11K",
    prompts: 340,
    rating: 4.7,
    verified: false,
  },
  {
    id: 6,
    name: "Sophia Brown",
    username: "@sophia",
    avatar: "🎬",
    bio: "Content Creator & Designer",
    specialization: "Content Creation",
    followers: "21K",
    prompts: 610,
    rating: 5.0,
    verified: true,
  },
];