import { MarketplaceItem } from "@/types/marketplaceItem";

export const marketplaceItems: MarketplaceItem[] = [
  {
    id: 1,
    title: "Ultimate SaaS Prompt Pack",
    creator: "Gopal",
    category: "Development",
    tool: "ChatGPT",
    price: "₹999",
    rating: 4.9,
    sales: "1.2K",
    featured: true,
  },
  {
    id: 2,
    title: "Midjourney Mega Collection",
    creator: "Alex",
    category: "Design",
    tool: "Midjourney",
    price: "₹1,499",
    rating: 4.8,
    sales: "980",
    featured: true,
  },
  {
    id: 3,
    title: "Playwright Automation Kit",
    creator: "Sarah",
    category: "Testing",
    tool: "ChatGPT",
    price: "₹799",
    rating: 4.9,
    sales: "850",
    featured: false,
  },
  {
    id: 4,
    title: "Instagram Viral Prompt Bundle",
    creator: "Emma",
    category: "Marketing",
    tool: "Claude",
    price: "₹699",
    rating: 4.7,
    sales: "1.5K",
    featured: true,
  },
  {
    id: 5,
    title: "Thumbnail Master Collection",
    creator: "Sophia",
    category: "Design",
    tool: "Flux",
    price: "₹599",
    rating: 4.8,
    sales: "730",
    featured: false,
  },
  {
    id: 6,
    title: "Cursor Developer Toolkit",
    creator: "John",
    category: "Development",
    tool: "Cursor",
    price: "₹1,199",
    rating: 4.9,
    sales: "910",
    featured: true,
  },
];