import { TrendingPrompt } from "@/types/trendingPrompt";

export const trendingPrompts: TrendingPrompt[] = [
  {
    id: 1,
    title: "Build SaaS Landing Page",
    category: "Development",
    tool: "ChatGPT",
    creator: "Gopal",
    likes: "5.2K",
    views: "42K",
    rating: 4.9,
    isTrending: true,
  },
  {
    id: 2,
    title: "Cinematic Portrait Prompt",
    category: "Photo Editing",
    tool: "Midjourney",
    creator: "Alex",
    likes: "4.8K",
    views: "38K",
    rating: 4.8,
    isTrending: true,
  },
  {
    id: 3,
    title: "Playwright Test Generator",
    category: "Testing",
    tool: "ChatGPT",
    creator: "Sarah",
    likes: "3.9K",
    views: "31K",
    rating: 4.9,
    isTrending: true,
  },
  {
    id: 4,
    title: "YouTube Thumbnail Prompt",
    category: "Design",
    tool: "Flux",
    creator: "Sophia",
    likes: "4.5K",
    views: "35K",
    rating: 4.8,
    isTrending: true,
  },
  {
    id: 5,
    title: "Instagram Reel Script",
    category: "Marketing",
    tool: "Claude",
    creator: "Emma",
    likes: "5.1K",
    views: "46K",
    rating: 4.9,
    isTrending: true,
  },
  {
    id: 6,
    title: "React Dashboard UI",
    category: "Development",
    tool: "Cursor",
    creator: "John",
    likes: "3.8K",
    views: "28K",
    rating: 4.7,
    isTrending: true,
  },
];